name: Lint

on:
  - push
  - pull_request

jobs:
  lint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: 'Setup Node'
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn -v
          yarn --frozen-lockfile
      - name: Run ESLint
        run: |
          node -v
          yarn run eslint .
